eng_alphabet = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
dots = 'ё%:!№;?.ij'
joint_alphabet = 'aceopxABCEHKMOPTXасеорхАВСЕНКМОРТХ'
eng_vowels = 'aeiouAEIOU'
eng_consonant = 'bcdfghjklmnpqrstvwxyzBCDFGHJKLMNPQRSTVWXYZ'